name: Package and Release Resource Pack

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP Archive
        run: |
            rm -rf .github
            rm -rf .git
            rm -rf .gitignore
            zip -r ../Foolish_Resource_Pack.zip .

      - name: Generate SHA-1 Hash
        id: hash
        run: |
          cd ..
          HASH=$(sha1sum Foolish_Resource_Pack.zip | awk '{ print $1 }')
          echo "SHA1: $HASH"
          echo "sha1=$HASH" >> $GITHUB_OUTPUT

      - name: Save hash to file named with hash
        run: |
          cd ..
          echo "${{ steps.hash.outputs.sha1 }}" > ${{ steps.hash.outputs.sha1 }}.txt

      - name: Upload Resource Pack and SHA1 to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ../Foolish_Resource_Pack.zip
            ../${{ steps.hash.outputs.sha1 }}.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}